# Generated by Django 2.2.3 on 2019-08-06 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_questions_time_and_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interest',
            new_name='InterestArea',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='emailid',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='questions',
        ),
    ]
