# Generated by Django 2.2.3 on 2019-08-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190806_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(max_length=40),
        ),
    ]
