# Generated by Django 2.2.3 on 2019-08-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190806_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
