# Generated by Django 2.2.3 on 2019-08-06 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190806_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='temp_id',
            field=models.ForeignKey(default=django.utils.timezone.now, max_length=40, on_delete=django.db.models.deletion.PROTECT, to='webapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=django.utils.timezone.now, max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
